doc/win64-mingw64-msys2/README.txt

I worked out a quick way to build a working VST plugin which can be used with ext-gui, on Windows 64-bit. It works nicely in Ardour.
I wanted to get the process down in writing to help anyone who might be interested in adding better Windows support to Zyn. I may attempt to add the support myself, but feel free to beat me to it, since I just want to actually use this software on Windows now for awhile, after spending 5 days documenting how to compile Ardour and Zyn on Windows :P
Let me know what you think of it, it was really hard to figure out!

Unofficial instructions for compiling on Win64 MinGW64 MSYS2

---

src/UI/MasterUI.fl

The idea is to update what's displayed when you go to : ZynAddSubFX menu -> File -> Copyright to something more updated/accurate.
I didn't test it. Please check if it's done correctly.

update copyright info on the GUI

---

src/Tests/CMakeLists.txt

Current version doesn't work if buildir not in root of source dir

fix path for save-osc test

---

src/Params/LFOParams.cpp

Adds the RAN LFO shape to the generated schema.

LFOParams: Add 'RANDOM' LFO shape in the rtosc::Ports structure

---

src/Misc/XMLwrapper.cpp

Loading my old qtractor-sessions started to crash on my Raspi. A remote debug
session lead to zynaddsubfx and the point of code:
Wih this modification the sessions load again without issues.

Fix crash with mxml V3

---

cmake/BashCompletion.cmake

BASHCOMP_PKG_PATH is supposed to replace BASHCOMP_USER_PATH if set, rather than be existing file/dir, since it is about to be created.

Fix BashCompletion.cmake output script

---

CMakeLists.txt
TODO-release.md

The build currently fails because of a missing file at the root of the build tree. This PR fixes it.

Bugfix: Removes occurences to HISTORY.txt

---

src/Misc/Master.cpp

Is there a way to overload functions in the OSC dispatcher? I first tried `noteOn:iiif`, but If I'd send an event, it would also trigger `noteOn:iii`, which is quite annoying.

Add microtonal support

---

src/Misc/MiddleWare.cpp
src/Tests/MiddlewareTest.h

This fixes a bug where zyn aborts after a midi program change to an undefined patch.  I can consistently reproduce this by sending midi bank change MSB, bank change LSB and then a program change to a program that is not defined in the bank.  For some reason this does not occur when sending a just a program change for a program not defined in the current bank on startup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zynaddsubfx/zynaddsubfx/40)

Fix abort on pgm change to undefined part

---

src/Params/ADnoteParameters.cpp

So, test.json in osc-bridge needs to be updated too, with the output from zynaddsubfx  -D option?
Like here in the version i just generated: [https://github.com/strongheart1/osc-bridge/commit/0d47f471b23d8a6106f1fa35a285641f435f1ebd](https://github.com/strongheart1/osc-bridge/commit/0d47f471b23d8a6106f1fa35a285641f435f1ebd) there are also other changes, due to envelope time parameter changes.

unison-size  minimum: 0 corrected to 1

---

src/Misc/MiddleWare.cpp

Before this, any realtime parameter change of PAD synth, e.g. filter,
triggered the "needPrepare" message, marking the PAD synth's "Apply
Changes" button.

Fix PAD filter changes needing prepare

---

src/Misc/Part.cpp
src/Params/EnvelopeParams.cpp
src/Params/EnvelopeParams.h
src/Synth/Envelope.cpp
src/UI/EnvelopeUI.fl

This modification can free up some cpu time when playing with many sustained notes with many voices with different decay times. It should not have any sonical impact because it removes inaudible voices only.

finish addsynth ENVs sustaining at 0 with 0 release to free up cpu

---

src/Effects/Distorsion.cpp

with this patch the waveform view in the distorsion effect reflects the effect of the AMT knob in zest (Pvolume par) in the way you hear it. At Pvolume=0 you hear no distorsion -> Transferfunction is linear. Now in waveview, too.

make /distorsion/waveform reflect the Pvolume par

---

src/Effects/Distorsion.cpp
src/Misc/WaveShapeSmps.cpp
src/Synth/ADnote.cpp
src/Synth/ADnote.cpp.orig

lp/hp filter in distorsion effect are only calculated if cutoff freq parameter is not at max/min value.
slow powf operations in waveshaper replaced by multiplications
some precalculations in adsynth to speed up linerar interp oscillator

performance improvements in distorsion and adnote

---

src/Misc/Microtonal.cpp

Tunings with numerators/denominators work during a session, but when loaded from a file, the values are limited to 0 <= x <= 127. This commit increases that limit to a safe one.
N.B. It's quite easy to end up with very complex fractions when tinkering with exotic tunings; see for instance the table at https://en.wikipedia.org/wiki/The_Well-Tuned_Piano#Tuning .

in fractional tunings, allow numerator/denominator greater than 127

---

src/Misc/WaveShapeSmps.cpp

drive values less than one (below CC value 44) together with offset make it possible to go though the transfer function at different spots. that allows in the result more gentle asymmetric transfer functions.

reduce minimum drive of square/cubic distorsion

---

.travis.yml
cmake/FindSndio.cmake
src/CMakeLists.txt
src/Nio/CMakeLists.txt
src/Nio/EngineMgr.cpp
src/Nio/SndioEngine.cpp
src/Nio/SndioEngine.h

This PR adds sndio support.
I had tested this on OpenBSD 6.7 (amd64), and saw both audio out and midi in.

Add sndio support

---

src/CMakeLists.txt

When building under CYGWIN, I got few errors because some stuff, like `usleep()`, was not declared.
Actually, everything already exists in CYGWIN, but when compiling under C++11, some prototypes and symbols are intentionally deactivated and they need to be activated manually with some macros like `_GNU_SOURCE`, `_BSD_SOURCE` or others.
The addition of the required macros in this commit allows to activate the required symbols and compile the sources successfully.

[CYGWIN] Add support for this platform.

---

cmake/FindOSS.cmake

When compiling for Windows, I discovered that CMake reported that OSS was found, which is not true since it is known to be unsupported by that platform.
I suggest to fix the included CMake script to avoid detection under WIN32 and also under APPLE.
This fix has been inspired by the FindOSS script implemented for GNUradio:
https://github.com/gnuradio/gnuradio/blob/master/cmake/Modules/FindOSS.cmake

[CMAKE] Fix detection of OSS

---

src/CMakeLists.txt
src/globals.h

Currently, only APPLE and FreeBSD can include C++ std::complex in globals.h.
Check if OS has C++ std::complex, and use this condition to include or not in globals.h, instead of checking OS macro.

Include <complex> other than APPLE and FreeBSD

---

src/CMakeLists.txt

"#ifdef HAVE_SCHEDULER" in Util.cpp does not work correctly,
since cmake always defines "add_definitions(-DHAVE_SCHEDULER=" except Darwin.
It should not define HAVE_SCHEDULER if OS does not have it.

Do not define HAVE_SCHEDULER if OS does not have it

---

src/Misc/Part.cpp

When building with mingw-w64, I suddently got this error:
```
[ 52%] Building CXX object src/CMakeFiles/zynaddsubfx_core.dir/Misc/Part.cpp.obj
src/Misc/Part.cpp: In lambda function:
src/Misc/Part.cpp:174:17: error: 'time' was not declared in this scope; did you mean 'ftime'?
174 |                 time (&rawtime);
|                 ^~~~
|                 ftime
src/Misc/Part.cpp:175:45: error: 'localtime' was not declared in this scope
175 |                 const struct tm* timeinfo = localtime (&rawtime);
|                                             ^~~~~~~~~
src/Misc/Part.cpp:176:17: error: 'strftime' was not declared in this scope; did you mean 'ftime'?
176 |                 strftime (p->loaded_file,23,"%F_%R.xiz",timeinfo);
|                 ^~~~~~~~
|                 ftime
make[2]: …
```

[WIN32] Fix error on missing time functions.

---

src/CMakeLists.txt

Some OS requires libX11 path to link, since it is sometimes placed under /usr/X11R6/lib/ etc.
This PR adds libX11 path to link directory.

Add libX11 path to link directory

---

src/CMakeLists.txt

Additional fix for merged PR #73 .
I had checked build on travis-ci only, and I should have thought about Windows build, too.
I think this PR is able to resolve this comment.
https://github.com/zynaddsubfx/zynaddsubfx/commit/4ad23b090e2ea64c637adfd41ffa81887080b43d#commitcomment-40545890
@carlo-bramini could you try to see if this PR resolves your issue, please ?

Get the X11 library path only if libX11 exists

---

src/UI/NSM.C

Since existing implementation does not check if `asprintf()` is executed successfully, I left modified code also in the same manner, to be sure that new code works exactly like the old one. Probably, it should just return an error, but the value is unknown to me.

[WIN32] Fix problem of missing asprintf()

---

src/Nio/CMakeLists.txt

Small fix for a missing CMake include. Compilation would fail when building with only JACK enabled because `CheckIncludeFiles` wasn't included. It wouldn't fail when for example ALSA was enabled as well because within the CMake config for ALSA it would include `CheckIncludeFiles` which made it work for JACK as well, it's probably gone unnoticed so far because of this.

src/Nio: Fix missing CMake include when JACK is enabled

---

src/Misc/MiddleWare.cpp

This leads to chained messages being sent to the backend *after* they
are forwarded themselves.

Let MwDataObj::chain use a queue

---

src/Misc/MiddleWare.cpp

Due to a gcc opt bug a piece of code was put in a separate function to
prevent gcc from optimizing it. Later versions of gcc inlined the
function and the bug reappeared. So now we explicitly tell gcc to not
optimize it.
https://github.com/zynaddsubfx/zyn-fusion-build/issues/65

Disable gcc optimizations for a specific function

---

src/Synth/LFO.cpp
src/Synth/LFO.h

fix a small bug that lets the biquad calculate also at unchanged cutoff value.

make the cutoff in LFO a member variable

---

src/Misc/Master.cpp
src/Misc/Master.h
src/Misc/MiddleWare.cpp
src/Misc/MiddleWare.h
src/Misc/Recorder.cpp
src/Misc/Recorder.h
src/Misc/Schema.cpp
src/Params/EnvelopeParams.cpp
src/Params/LFOParams.cpp
src/Params/PADnoteParameters.cpp
src/Params/SUBnoteParameters.cpp
src/Tests/check-ports.rb
src/main.cpp

Split MW snoop ports into non-RT ports and other snoop ports, and then
* Let path-search iterate over non-RT ports, too (e.g. to let port-checker see those ports)
* Let save_osc save non-RT ports, too (to build complete savefiles)
This commit is a bug fix, because currently, port-checker does not look at the non-RT MW-ports, and it would make the SaveOsc tests fail if the test xmz would have non-RT ports changed (in comparison to the default values).
This commit is preparation for the wavetable-branch (SaveOsc failed there with the new non-RT ports).

path-search/save_osc: include non-RT ports

---

src/Params/FilterParams.cpp

This came up by a compiler warning. Should be easy to review.

FilterParams: Fix timestamps updating on request

---

src/Effects/DynamicFilter.cpp
src/Effects/DynamicFilter.h
src/Effects/EffectMgr.cpp
src/Misc/Config.cpp
src/Misc/Master.cpp
src/Misc/Microtonal.cpp
src/Misc/MiddleWare.cpp
src/Misc/Part.cpp
src/Misc/Stereo.cpp
src/Misc/Stereo.h
src/Params/Controller.cpp
src/Params/Controller.h
src/Params/EnvelopeParams.cpp
src/Plugin/CMakeLists.txt
src/Plugin/ZynAddSubFX/ZynAddSubFX-UI.cpp
src/Synth/OscilGen.cpp
src/UI/EnvelopeFreeEdit.cpp
src/UI/EnvelopeUI.fl
src/UI/FilterUI.fl
src/UI/Fl_Osc_Pane.cpp
src/UI/Fl_Osc_Slider.cpp
src/UI/Fl_Osc_TSlider.cpp
src/UI/Fl_Resonance_Graph.cpp
src/UI/FormantFilterGraph.cpp
src/UI/NSM.C
src/UI/PartUI.fl
src/UI/VirKeyboard.fl
src/UI/WidgetPDial.cpp
tlsf/tlsf.c

Almost all warnings for gcc 10.2.0 and clang 11.0.0 are gone after this PR (together with #100 and #103).

Fix compiler warnings

---

src/CMakeLists.txt

I'm trying to compile ZynAddSubFx with MinGW-W64, but I got this error when CMake configured the build:
```
CMake Error at src/CMakeLists.txt:455 (string):
string sub-command STRIP requires two arguments.
```
While CMakeLists.txt file does syntactically contain two arguments, ${FLTK_LDFLAGS} can be empty. If this happens, then the string() function never receives the correct number of parameters, which then sees just one. If the string could be empty, then CMakeLists.txt must quote it.
EDIT: I just discovered that into `doc/win64-mingw64-msys2/README.txt` there is a `sed` command for patching the CMake file, but actually it is a bit unknown to me the reason because it has not been applied directly to `CMakeLists.txt`, since in my opinion it should be the right way to do it.

[CMAKE] Fix configuration error on Windows.

---

src/Misc/Master.cpp

This is a minor typo, but has an impact on documentation IIUC. 
Apologies if you feel I've been spamming you with minor fixes - I'm still learning the projects' work style. I can also package those small modifications with larger ones if you prefer fewer PRs.

Fix a typo: depricated -> deprecated

---

src/Plugin/ZynAddSubFX/ZynAddSubFX-UI-Zest.cpp

DAWs like REAPER support saving VST's state as so-called "user presets"
(or directly saving it into project file). And in most VST plugins,
when you load a "user preset", the state (aka. configurations) of that
plugin is restored, and the UI is also updated according to the state.
For example, when you load a state for Dragonfly Reverb, all the knobs
will point to where you've configured at that time.
However, currently ZynAddSubFX cannot do this whatever the UI module
I use (Zest or NTK). It can still load state, but the UI still keeps
unchanged, not showing my manually-configured parameters. This will
be great trouble to DAW users.
To solve this issue, I need to invoke a method to update Zest UI in
DISTHRO::UI::stateChanged(). This event is raised every time when VST
host loads presets, …

Plugin: Zest: Auto update UI when loading presets from host

---

src/UI/OscilGenUI.fl

The phase/mag ports already call prepare, no reason to call it twice.
Checks done:
* Tested PAD and AD that change of the mag and phase sliders did affect all oscilloscopes + sound
* Added a printf into "prepare:b". It now appears half the time as on master.

UI: Remove duplicate OscilGen prepare call

---

src/Misc/MiddleWare.cpp
src/Synth/OscilGen.cpp

Prior to this commit, OscilGen's prepare/magnitude/phase ports prepare
data and send it to prepare:b. Since we have no RT thread in OscilGen
anymore, this commit does not send anything to the RT side anymore -
instead, code where the new FFT data has been sent is replaced by the
content of the prepare:b port.
This fixes memory leaks, because prepare:b did not "/free" the freqs
prior to this commit.

Move prepare:b to where it has been called

---

doc/README.txt
src/Misc/MiddleWare.cpp
src/Misc/PresetExtractor.cpp

The fix was to add a missing call to rDoc. Also documented the /quit endpoint.

Fixed the documentation for a few OSC endpoints.

---

src/Synth/OscilGen.cpp

add a more analog style lp filter based on the sallen-key transfer function to oscilgen lpsk2
params are cutoff and resonance.

add sallen-key lp filter to oscilgen

---

src/UI/guimain.cpp

Additional comments are added to explain that `--embed` runs zyn as a
plugin, and that window embedding only works with NTK.
falkTX, can you please review this?

Fix compiler warning (unused variable)

---

src/Misc/MiddleWare.cpp
src/Misc/MiddleWare.h
src/Plugin/ZynAddSubFX/ZynAddSubFX-UI.cpp
src/Plugin/ZynAddSubFX/ZynAddSubFX.cpp

This is a draft PR that I could not test, because I don't know how to use this functionality. falkTX said that these functions can not be accessed by Lv2, but by using jack "directly", but I gave up trying to find out how. fundamental said that I could copy the code mostly from `src/Nio/InMgr.cpp`.
As I could not test this, it's questionable if anything of this works. 
Intention of this PR: Fix compiler warnings (unused parameters).

Implement ZynAddSubFX::loadProgram

---

ExternalPrograms/Spliter/readme.txt
NEWS.txt
src/Misc/Microtonal.cpp
src/Misc/Microtonal.h
src/Misc/Part.cpp
src/Misc/XMLwrapper.h
src/Nio/SndioEngine.cpp
src/Params/PADnoteParameters.cpp
src/Synth/Envelope.cpp
src/UI/MasterUI.fl
src/UI/MicrotonalUI.fl
src/UI/OscilGenUI.fl
src/UI/PADnoteUI.fl
src/globals.h
style.cfg

Found via `codespell -q 3 -L continous`

Fix various typos

---

src/Misc/Config.cpp
src/Misc/Config.h
src/Misc/Master.cpp
src/Misc/Master.h
src/Misc/MiddleWare.cpp
src/Nio/AlsaEngine.cpp
src/Nio/AudioOut.h
src/Nio/JackEngine.cpp
src/Nio/JackMultiEngine.cpp
src/Nio/Nio.cpp
src/Nio/Nio.h
src/Nio/OssEngine.cpp
src/Nio/OssMultiEngine.cpp
src/Nio/OutMgr.cpp
src/Nio/OutMgr.h
src/Output/DSSIaudiooutput.cpp
src/Plugin/ZynAddSubFX/ZynAddSubFX.cpp
src/main.cpp

in this branch the StereoCompressor in the audio output will be changed to be optional an per default off to keep compatibility.

make Compressor in Audio Output optional

---

src/Containers/NotePool.cpp
src/Containers/NotePool.h
src/Misc/Part.cpp
src/Misc/Part.h
src/Tests/KitTest.cpp
src/Tests/guitar-adnote.xmz

Here's my attempt at adding a settable voice limit per part (Pvoicelimit), similar to Pkeylimit, except it really limits the number of voices sounding not just the number of notes actually being played. This way, sounds with long release times won't cause xruns when playing lots of notes. In effect, the part will behave like a classic synthesizer with a fixed number of voices.
Caveat: voices which are silenced are entombed rather than killed, meaning that for a brief period after stealing voices there will be more voices playing than the voice limit governs. I felt this was still preferable to killing the voices as that results in audible clicks, and the voice limit is not a hard DSP limit anyway.
Effort has been made to select the most appropriate note to steal every time

Voice limit

---

src/Misc/MiddleWare.cpp
src/Params/PADnoteParameters.cpp

Return samples to non-realtime thread for deallocation when new
samples are installed to avoid old unused samples leaking memory.
Fix suggested by Mark McCurry.

Avoid PAD samples leaking memory (#291)

---

src/CMakeLists.txt

The availability of the "fistpl" x86 instruction was tested with a
direct call to the "as" command. In case the project is cross-compiled
to another architecture, the host compiler is tested instead the
target one. This was leading to compilation failures. This commit now
perform the test using the target compiler defined in CMake, which
fixes cross-compilation. This commit does not change the behavior
when doing a native compilation, as the host and target compiler are the
same.
Signed-off-by: Julien Olivain <ju.o@free.fr>

src/CMakeLists.txt: use the target compiler during config tests

---

src/Misc/Microtonal.cpp
src/Nio/Nio.cpp
src/Synth/WatchPoint.cpp

This pull request fixes few compiler warnings reported by gcc 11 on Linux.
Those changes are mostly cosmetic and are not changing the behavior.

Fix gcc warnings

---

src/DSP/FFTwrapper.cpp
src/DSP/FFTwrapper.h
src/Params/PADnoteParameters.cpp
src/Synth/OscilGen.cpp
src/Synth/OscilGen.h

Reason for PR: parallelize `FFTwrapper` => remove its buffers.
Solution: run directly on input/output buffers => ensure that these are big enough, using new classes `FFTsampleBuffer` and `FFTfreqBuffer`.
Alternative solution (not realized): pass temporary buffers to `FFTwrapper` for every FFT/IFFT (probably more complicated, would take more memcpys)

Removing buffers from FFTwrapper

---

src/Misc/Master.cpp
src/Misc/Part.cpp
src/Misc/Part.h

This turned out to be slightly more complex than I anticipated, and also there already seemed to be code which disables a part gracefully which has not actually been used for a while.

Jack multi part mute

---

src/Misc/MiddleWare.cpp
src/Tests/PluginTest.cpp
src/Tests/SaveOSC.cpp

This uses a fixed config in tests, instead of relying on the user
config.
For `MiddleWare::saveParams`, the second master (which controls the
saving) must have the same config values for `SaveFullXml` as the first
master (the original one). Otherwise, they dump different XMLs which can
not be compared.

Make tests independent of config

---

src/Misc/Master.cpp

Fix inverted LR panning in part outputs in multi mode. This was due
to LR being swapped in three places, in conjunction with the part
panning control being inverted:
- Mixer VU meter LR was swapped
- Part VU meters LR were swapped
- Audio mix output LR was swapped
A partial clue to the above (apart from the obviously inverted
LR part panning) was that panning in the parts effects (e.g. Echo)
was audibly ok in multi mode, but the VU meter indication was
swapped Left-Right. At the same time, the summed output from the
mixer exhibited inverted panning with regards to panning set in a
part effect.

Misc/Part: Fix LR swap in multi mode (#330)

---

CMakeLists.txt
src/CMakeLists.txt

CMakeLists.txt:
Also check for librtosc-cpp when `ZYN_SYSTEM_RTOSC=ON`.
src/CMakeLists.txt:
When `ZYN_SYSTEM_RTOSC=ON`, link against system provided librtosc and
librtosc-cpp, else link against the local targets (exposed via the rtosc
submodule).
This is a follow-up to https://github.com/zynaddsubfx/zynaddsubfx/pull/170 to ensure proper linking against system provided libraries.

Allow linking against system rtosc and rtosc-cpp

---

CMakeLists.txt
src/Misc/Part.cpp
src/Params/Controller.cpp
src/Params/Controller.h
src/Synth/Portamento.cpp
src/Synth/Portamento.h
src/Tests/KitTest.cpp
src/Tests/PortamentoTest.cpp
src/Tests/guitar-adnote.xmz

Implement auto mode for portamento. This decouples the requirement to play legato to get portamento for the mono and legato modes from the mode itself, and allows activation of portamento in poly mode to be optionally controlled by legato playing, governed by a new portamento parameter.
I've let the automode member for the Controller.portamento struct be an unsigned char as all others are unsigned chars, and it didn't seem right to attempt to clean this up at this time.
In order to set auto portamento mode selectively when loading older patches, based on the key assign mode, I've bumped the revision version number. I don't know if this is an ok thing to do at this point.

Auto portamento mode

---

src/Params/Controller.cpp
src/Params/Controller.h

When modwheel.depth or modwheel.exponential is changed, update the
modulation amount directly, rather than only when a new modwheel
value is received. This results in a more positive user experience,
otherwise it seems like changing the depth or exponential
parameters does not have any immediate effect.

Update mod amount when depth/exp changed (#345)

---

doc/controller.txt

In the recent auto portamento updates I forgot about updating the
documentation, which is remedied by this commit.

Add auto portamento description to documentation

---

src/Misc/Master.cpp

This `tmp` var doesn't appear to be doing anything, and is throwing a compiler warning. Can it be removed?

Remove unused variable in demo version silencing code

---

src/globals.h

Decrease the rate of smooth_float changes to make filter parameters
appear less sluggish. Otherwise it can take several seconds for
a parameter to reach the value set by a knob.
I don't know if this change has other consequences than the rate of parameter change when changing parameters in the UI, so this is more of a suggestion than a die hard fix.

globals.h: Increase smooth_float speed (#347)

---

src/DSP/SVFilter.cpp

In the setstages() method, only call cleanup() when needed,
i.e. when the number of stages is actually changed (same as
in AnalogFilter.cpp).
(The reason this is a problem is because setstages() is
called whenever the frequency, Q, filter tracking or gain
is changed in the UI).

SVFilter.cpp: Avoid clicks when UI updates freq, Q or gain (#348)

---

src/Containers/NotePool.cpp
src/Containers/NotePool.h
src/Misc/Part.cpp
src/Tests/KitTest.cpp

Use the correct NotePool method to release keys, which set the
released keys in the RELEASED state, rather than bypassing the
note pool and directly calling the releasekey() method for the
engine(s).

Part, NotePool: Use correct method to release keys (#346)

---

src/Misc/MiddleWare.cpp

Correctly handle messages that have been queued up from the backend
while performing a doReadOnlyOp, rather than sending them
back to backend.
This gets rid of messages like the following when doing a write
operation from the UI:
Unknown address<BACKEND:online> /vu-meter:ffffffffffffffffffffffffffffffffffffff
Unknown address<BACKEND:online> /broadcast:
Unknown address<BACKEND:online> /active_keys:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

MiddleWare: Handle queued up messages during doReadOnlyOp

---

src/Misc/MiddleWare.cpp

Slightly unsure of this one, but forward and broadcast seem to be mutually exclusive, and the layout of the code indicates that there is a missing else.
It doesn't seem to fix any observable bug though, so if there's any doubt just drop this PR. I just came across it while looking debugging and thought I'd mention it is it looks odd.

Add likely missing else

---

src/Params/ADnoteParameters.cpp
src/Params/ADnoteParameters.h
src/Synth/ADnote.cpp
src/Synth/ADnote.h
src/Tests/guitar-adnote.xmz

this commit makes it possible to disable the filter cutoff midi control (CC74) per voice. This is good for pitch tuned (comb) filters.

Pfilter fc ctl bypass

---

src/Effects/Distortion.cpp

This fixes a bug introduced in 85ed5029787cbbc3b4ea50bc18b9182526d923eb. That commit accidentally multiplied the preset value for volume by 3/2, instead of by dividing it ("lowering") by 3/2.
This fixes knobs displaying values like "190" and presets being too loud.

Fix distortion effect multiplier

---

src/Effects/Sympathetic.cpp

Analogous implementation to
4e0b22f267f4254ad9deed74856d9155aef55848, but this time, for the Sympathetic effect.

Fix sympathetic effect multiplier

---

src/Effects/DynamicFilter.cpp
src/Params/FilterParams.cpp
src/Params/FilterParams.h

This is likely a fixup of b650636e306237397ef106b86fc2aaa35ec5182b, where those params have been turned into mostly unused dummy params, but the DynFilter code which uses them has been forgotten to adapt.
So this code fixes the DynFilter presets, so they sound like in 2017 again.
Additionally, this code also removes the dummy variables, which have no use as class variables since 2017.

Fixup DynFilter presets after corruption in 2017

---

src/Synth/OscilGen.cpp

This skips an unnecessary re-computation of OscilGen's `basefuncFFTfreqs`.
Before this patch, not only runtime is wasted, but the redundant FFT can slightly modify the base func FFT freqs, which can cause issues when comparing savefiles.

OscilGen: Skip no-ops for custom base funcs

---

src/Effects/EffectMgr.cpp
src/Params/ADnoteParameters.cpp

This is due to a bug, which is documented in rtosc tests.

Switch some ports so apropos() works for them

---

src/Effects/Alienwah.h
src/Effects/Chorus.h
src/Effects/Distortion.h
src/Effects/DynamicFilter.h
src/Effects/EQ.h
src/Effects/Echo.h
src/Effects/Phaser.h
src/Effects/Reverb.h
src/Effects/Sympathetic.h

This fixes warnings like
```
Distortion.cpp:117:5: Call to virtual method 'Distortion::setpreset' during construction bypasses virtual dispatch [clang-analyzer-optin.cplusplus.VirtualCall]
```

Effects: Get rid of compiler warnings

---

src/Misc/Part.cpp
src/Params/ADnoteParameters.cpp
src/Params/FilterParams.cpp
src/UI/PartUI.fl

* Part.cpp: keylimit is 100 in some old savefiles
* ADnoteParameters.cpp: unison size was 0 or >50 while developing the zest UI
* FilterParams.cpp: basefreq was sometimes slightly lower than "min" (rounding errors)

Don't load invalid values from XML savefiles

---

src/Misc/Part.cpp
src/Params/Controller.cpp

This probably wouldn't show up on any other platform, as it is based on something sending CC#78 (Resonance Bandwidth) to Zynaddsubfx (without updating Resonance Bandwidth Depth first), but Zynthian does, and when it happens it triggers a bug which I believe causes disruption of the audio when Resonance is enabled due to the relbw struct member being uninitialized. I didn't debug it further than this, basically just copying the code from the way Resonance Center is handled. Testing adjusting Resonance Center and Resonance Bandwidth using the Zynthian built-in GUI now behaves in a sane manner so it seems to be the correct fix.
While debugging I also found a discrepancy in the way incoming CC messages for Resonance Center and Resonance Bandwidth are handled, again, essentially copying code …

Fix issue with ADDsynth part going silent in Zynthian when Resonance enabled

---

src/CMakeLists.txt

It's a simple change that will make compiling zynaddsubfx with the ntk UI easier for newcomers.
I checked that this PR doesn't break the windows and mac builds.
-- Commit message:
This fixes several confusing issues that happen when both fltk and ntk are installed. The default is to compile using ntk, but the fltk installs somehow shadows ntk-fluid, leading to fl files not being converted to cxx. This only shows at compilation time, very far from the original issue.
This changes does two things:
- prevent fltk fluid from shadowing ntk-fluid
- make the cmake invocation idempotent: when the FLTK_FLUID_EXECUTABLE is not unset, the first cmake invocation fails, but the second one goes through because FLKT_FLUID_EXECUTABLE is set to the default value 'fluid'.

Make cmake error out when ntk-fluid is not found

---

src/Misc/MiddleWare.cpp
src/Misc/MiddleWare.h
src/Tests/SaveOSC.cpp
src/UI/Connection.cpp
src/UI/NSM.C

@fundamental Can you please review this? The implementatin of `transmitMsgGui*` is exactly like we discussed in Discord, so you don't need to check this. But it would be nice if you can check if I replaced `transmitMsg*` by `transmitMsgGui*` in the right places and did not forget elsewhere - I wrote down the justification below in the commit description. Thanks on advance.
--- commit description below ---
This fixes an issue only related to in-process remotes, aka "GUI".
`MwDataObj::reply` uses `MiddleWareImpl::sendToCurrentRemote`, which sometimes uses `MiddleWareImpl::last_url` as the reply URL. However, the latter variable is only being set in `handler_function`, i.e. in the liblo callback, so in case the GUI was last, `last_url` has not been updated, and `MwDataObj::reply` sends to …

Implement/use transmitMsgGui

---

src/Synth/ADnote.cpp
src/Synth/PADnote.cpp
src/Synth/SUBnote.cpp
src/Tests/AdNoteTest.cpp

Fix panning direction for the individual synths as noted in the issue.
Also fix the ADnote test which actually is panning dependent. Simple fix, just use the R channel from the synth output instead of the L channel (this also ensures a certain amount of backwards traceability rather than extracting new values to compare with in the applicable tests).

Fix individual synth panning direction (#376)

---

src/Misc/Bank.cpp
src/Misc/Bank.h
src/Misc/Config.cpp
src/Misc/Util.cpp
src/Misc/Util.h
src/Params/PresetsStore.cpp

Alternative to #295 to fix loading builtin banks if `ZYN_DATADIR` changes.
```xml
...
<BANKROOT id="4">
<string name="bank_root">/nix/store/2w3a6jhxm3y6kb4a0fnbxsh2isc4fbf6-zynaddsubfx-3.0.6/share/zynaddsubfx/banks</string>
</BANKROOT>
<PRESETSROOT id="3">
<string name="presets_root">/nix/store/2w3a6jhxm3y6kb4a0fnbxsh2isc4fbf6-zynaddsubfx-3.0.6/share/zynaddsubfx/presets</string>
</PRESETSROOT>
...
```
```xml
...
<BANKROOT id="4">
<string name="bank_root">$ZYN_DATADIR/banks</string>
</BANKROOT>
<PRESETSROOT id="3">
<string name="presets_root">$ZYN_DATADIR/presets</string>
</PRESETSROOT>
...
```

Lazily expand `ZYN_DATADIR`

---

src/Synth/OscilGen.cpp

This port is buggy, so we disable it, in the same
way `basefuncFFTfreqs::b` had already been disabled.

Disable `magnitude#128::c:i` for port checker

---

.github/workflows/ccpp.yml
CMakeLists.txt
src/CMakeLists.txt
src/Misc/MiddleWare.cpp
src/UI/MasterUI.fl
src/UI/OscilGenUI.fl
src/UI/PartUI.fl
src/UI/SUBnoteUI.fl

* Add Werror option and use it in CI
* Add -Wno-stringop-truncation because it cannot be fixed with code
* Don't show warnings in NTK headers
* Fix warnings in code
* Raise CMake minimum version to 3.5 (due to deprecation warnings)
* Update RTOSC correspondingly

Add -Werror support, CMake cleanup

---

src/Plugin/ZynAddSubFX/ZynAddSubFX-UI-Zest.cpp
src/main.cpp

Also, this commit starts removing `-DZynFusionDir` from macOS - it could have never worked there, due to the `LD_LIBRARY_PATH` not existing there.

Plugin: Also accept `-DZynFusionDir`

---

doc/effects.txt
src/Effects/Chorus.cpp
src/Effects/Chorus.h
src/Effects/EffectLFO.cpp
src/Effects/EffectLFO.h
src/UI/EffUI.fl

this adds a new chorus mode ensemble, that attempts to realize the three-phase chorus 
once established by the Roland RS202 string synthesizer
https://www.soundonsound.com/reviews/roland-rs202-multivox-mx202-retrozone
https://www.florian-anwander.de/roland_string_choruses/
more info about 3 phase choruses:
http://jhaible.com/legacy/triple_chorus/triple_chorus.html
gui at: https://github.com/mruby-zest/mruby-zest-build/pull/113
(Write your PR description here)
- No trailing whitespace?
- Are all included headers necessary?
- No compiler warnings?
- No spell errors in documentation? (new words must be appended to `doc/wordlist.txt`)

new chorus mode - Roland Ensemble
