src/UI/MasterUI.fl, src/main.cpp
=> Update copyright mentions

doc/Makefile
As mentionned in https://sourceforge.net/p/zynaddsubfx/code/merge-requests/6/
=> Move the generation of chunked html pages to asciidoctor

CMakeLists.txt, zynaddsubfx-jack-multi.desktop
Would be handy to initially start zyn with per-instrument channels.
=> desktop launcher for multi-channel jack outputs

src/Misc/Master.cpp
Should fix https://github.com/zynaddsubfx/zyn-fusion-issues/issues/173. I might not have done this correctly :p
=> Save and load slot names

cmake/BashCompletion.cmake, doc/CMakeLists.txt, doc/bash-completion/CMakeLists.txt, doc/bash-completion/zynaddsubfx.in, src/Nio/Nio.cpp, src/Nio/Nio.h, src/main.cpp
Details:
* Add bash completion
* Add parameters `list-inputs` and `list-outputs`
* Choose the preferred spelling `preferred` for `prefered`
=> Add bash completion

src/Params/ADnoteParameters.cpp, src/Params/FilterParams.cpp, src/Params/PADnoteParameters.cpp, src/Params/SUBnoteParameters.cpp, src/Tests/UnisonTest.h
Should fix https://github.com/zynaddsubfx/zyn-fusion-issues/issues/99 .
=> Tweak filter defaults

src/Params/SUBnoteParameters.cpp, src/Params/SUBnoteParameters.h, src/Synth/SUBnote.cpp, src/Tests/guitar-adnote.xmz
Hi I convert amp velocity scale function to float in subpar!
=> convert subpar/ampvelocityscale to float

src/Params/SUBnoteParameters.cpp, src/Params/SUBnoteParameters.h, src/Synth/SUBnote.cpp, src/Tests/guitar-adnote.xmz
Hi I have change volume to dB in subpar/amp. I have tested myself it seem to be working!
=> change subpar/amp volume to dB

src/Misc/Master.cpp, src/Synth/ADnote.cpp, src/Synth/ADnote.h, src/Synth/PADnote.cpp, src/Synth/PADnote.h, src/Synth/SUBnote.cpp, src/Synth/SUBnote.h, src/Synth/WatchPoint.cpp, src/Synth/WatchPoint.h, src/Tests/AdNoteTest.h, src/Tests/CMakeLists.txt, src/Tests/PadNoteTest.h, src/Tests/SubNoteTest.h, src/Tests/TriggerTest.h, src/Tests/WatchTest.h
=> (WIP) Adding Watch Points for signal scope

src/Synth/ADnote.cpp
Minor change to watch point position for add synth
=> fix mixvoice issues in oscill

src/Misc/Master.cpp, src/Misc/Master.h, src/Misc/MiddleWare.cpp
Can you please review?
When done, please merge with a **regular merge commit**, rather than squashing or rebasing.
=> Dead backend fixes

src/Effects/Distorsion.cpp, src/Effects/Distorsion.h, src/Misc/WaveShapeSmps.cpp, src/Misc/WaveShapeSmps.h, src/UI/EffUI.fl, src/UI/OscilGenUI.fl
This is WIP.
A PR from @friedolino78 , imported from patch 43.
=> Distorsion

src/Misc/WaveShapeSmps.cpp, src/Synth/OscilGen.cpp
now with corrected rtosc dependency
=> fix in distorsion function 7 (limiter) and new waveshapers in oscilgen

src/CMakeLists.txt, src/DSP/FFTwrapper.h, src/Misc/Time.h, src/Params/FilterParams.h, src/Params/PADnoteParameters.cpp, src/Synth/OscilGen.cpp
@fundamental Can you please check if the warning options here make sense to you and the resulting code changes look justified?
P.S.: This is a draft, please don't merge yet.
=> Warnings padsynth oscilgen

doc/nrpn.txt, src/Misc/Master.cpp, src/Nio/MidiIn.cpp
implementation of my proposal to use only midi channel 0 for master insertion effects and the other channels for the respective part's insertion effects.
=> nprn controllers for part insert effects

src/Misc/Part.cpp
last fix was not complete
filename was created but not used
now works is as intended
=> fix of fixed savexml port

src/Params/EnvelopeParams.cpp, src/Params/EnvelopeParams.h, src/Synth/Envelope.cpp, src/Synth/Envelope.h
New Feature: Repeating ENVs. Only a few lines of code, but lots of fun to play with.
=> make ENVs repeatable

src/Misc/Master.cpp, src/Misc/MiddleWare.cpp
Probably trivial to review. :smile:
=> Message fixes

src/Params/EnvelopeParams.cpp
problem with seems to be solved.
=> fix default values for ENV time params

src/DSP/AnalogFilter.cpp, src/DSP/AnalogFilter.h, src/DSP/CMakeLists.txt, src/DSP/FormantFilter.cpp, src/DSP/FormantFilter.h, src/DSP/SVFilter.cpp, src/DSP/SVFilter.h, src/DSP/Value_Smoothing_Filter.cpp, src/DSP/Value_Smoothing_Filter.h, src/Misc/Master.cpp, src/Misc/Master.h, src/Misc/Part.cpp, src/Misc/Part.h, src/Params/Controller.cpp
As before, rebased onto current master (with conflict resolved).
=> Smooth filter cutoff and fix volume and expression interaction

src/Plugin/ZynAddSubFX/ZynAddSubFX.cpp
This is mostly what wikipedia/our README/our website say. Feel free to improve.
=> [skip ci] Implement ZynAddSubFX::getDescription

src/Misc/Master.cpp, src/UI/ADnoteUI.fl, src/UI/MasterUI.fl, src/UI/guimain.cpp
Fixed some minor string buffer size issues, which could lead to non-zero terminated strings or buffer overflow.
Fixed an "unused variable" warning due to code being preprocessed out.
=> Fixed a few compiler warnings

src/Params/EnvelopeParams.cpp, src/Params/EnvelopeParams.h
this has the advantage that the ADSR ports can be still used in freemode. use case especially ADSR controls via midi CC.
=> keep ENV knobs in sync in free mode

src/Misc/Master.cpp, src/Misc/Master.h, src/Misc/MiddleWare.cpp
(needed for large amounts of controllers)
=> re-enable classic midimapper and add support for NRPNs

src/Misc/Time.h, src/Params/LFOParams.cpp, src/Params/LFOParams.h, src/Synth/ADnote.cpp, src/Synth/LFO.cpp, src/Synth/LFO.h, src/Synth/PADnote.cpp, src/Tests/AdNoteTest.cpp, src/Tests/WatchTest.cpp, src/Tests/guitar-adnote.xmz
this adds a small feature, that I saw in a tutorlas for creating pad sounds in Serum
It lets the LFO fadein after the start delay over a specified amount of time.
used for frequency the spectrum can look like this:
[https://imgur.com/a/G3d8j9H](https://imgur.com/a/G3d8j9H)
=> add LFO fade in feature

src/Effects/EffectMgr.cpp, src/Effects/EffectMgr.h, src/Misc/Master.cpp, src/Misc/Time.h, src/Params/LFOParams.cpp, src/Params/LFOParams.h, src/Synth/LFO.cpp, src/Synth/LFO.h, src/Tests/guitar-adnote.xmz
this branch makes LFO frequency and some Effect delay times syncable to global time.tempo (with a rational factor multiplyer)
this allows relative frequencies and polyrhythmic LFO combinations in different voices or amp/freq/filter.
=> Bpm Sync internal

src/Misc/Config.cpp, src/Misc/Config.h, src/Misc/Master.cpp, src/Misc/Master.h, src/Misc/Part.cpp, src/Misc/XMLwrapper.cpp, src/Misc/XMLwrapper.h, src/UI/ConfigUI.fl
I've taken onboard earlier comments and tested this again.
=> Add an option to include disabled parts in the XML save file

src/Misc/Master.cpp, src/Misc/MiddleWare.cpp, src/Misc/PresetExtractor.cpp, src/Misc/Util.h, src/Params/ADnoteParameters.cpp, src/Params/EnvelopeParams.cpp, src/Params/FilterParams.cpp, src/Params/LFOParams.cpp, src/Params/PADnoteParameters.cpp, src/Params/SUBnoteParameters.cpp, src/Synth/Resonance.cpp, src/Tests/AdNoteTest.cpp, src/Tests/KitTest.cpp, src/Tests/MemoryStressTest.cpp, src/Tests/MessageTest.cpp, src/Tests/MiddlewareTest.cpp, src/Tests/PadNoteTest.cpp, src/Tests/PluginTest.cpp, src/Tests/SubNoteTest.cpp, src/Tests/TriggerTest.cpp, src/Tests/UnisonTest.cpp, src/Tests/WatchTest.cpp, src/Tests/valgrind-suppressions.txt
Now ready to review.
Should not be anything new after the IRC discussions.
Fixes #160
=> Fix all tests to pass valgrind's leak checks

.github/workflows/ccpp.yml
.github/workflows/ccpp.yml:
Build in an Arch Linux container against system rtosc and install the
resulting software.
=> Add CI integration for Arch Linux

doc/controller.txt
While trying to dig out how the modulation depth and exponential controls in the part panel actually work, I decided to try and document them for future reference
Please do read through to verify that I've gotten it right.
=> Add modwheel and assocated parameters documentation

src/Params/Controller.cpp, src/Params/Controller.h
Here I've done the same thing with the rest of the controller parameters as for the mod wheel. I've created two separate commits, one for controllers that have a depth parameter, and one for controllers that have enable toggles.
=> Update rest of controllers

src/Misc/Part.cpp
When the MIDI All Notes Off is received, this is equated to a
note off for all currently playing keys, which is not the
same as releasing all playing voices, as the latter does not
take into consideration the sustain pedal state.
This is noticable when playing Roland keyboards, which habitually
emit an All Notes Off message whenever all keys are released.
Tested with a Roland D-10 synth, which has the typical Roland behavior.
=> Part.cpp: Fix all notes off

src/Plugin/ZynAddSubFX/ZynAddSubFX.cpp
Behavior is now consistent with the standalone version.
=> Plugin/ZynAddSubFX: Handle Bank Select MSB and LSB

src/Misc/MiddleWare.cpp
Use the newly introduced read lookahead feature in ThreadLink in doReadOnlyOp and friends.
=> Readonlyops use lookahead

src/DSP/CombFilter.cpp, src/Effects/CMakeLists.txt, src/Effects/CombFilterBank.cpp, src/Effects/CombFilterBank.h, src/Effects/EffectMgr.cpp, src/Effects/Sympathetic.cpp, src/Effects/Sympathetic.h, src/UI/EffUI.fl, src/UI/MasterUI.fl, src/globals.h
this branch uses a comb filter bank to emulate the resonance of passive strings in a piano.
=> add sympathetic resonance effect

NEWS.txt, TODO-release.md
Also adjusted TODO-release.md to take into account the actual configurations that can be compiled.
=> Updated NEWS.txt before a release

src/Effects/Sympathetic.cpp
=> Sympathetic: Make "Generic" a preset

src/Tests/CMakeLists.txt, src/Tests/PortChecker.cpp
Only for testing the build before destroying the master...
=> Use rtosc's liblo_server class from tests

.github/workflows/ccpp.yml, src/Misc/MiddleWare.cpp, src/Params/ADnoteParameters.cpp, src/Params/SUBnoteParameters.cpp, src/Synth/OscilGen.cpp
Let's see what CI has to say...
=> github: Extensive tests on master/PR review

src/Params/ADnoteParameters.h, src/Params/Controller.h, src/Params/EnvelopeParams.h, src/Params/FilterParams.h, src/Params/LFOParams.h, src/Params/PADnoteParameters.h, src/Params/SUBnoteParameters.h
Had to include <cstdint> in a few more files for compilation to be successful
=> fixed cstdint issue in msys2/mingw64 windows compilation

src/DSP/CombFilter.cpp, src/Params/FilterParams.cpp
the combfilters with negative gain coefficients are quite handy for example to reduce even harmonics
=> add negative Combfiltertypes

src/Params/ADnoteParameters.cpp, src/Params/ADnoteParameters.h, src/Synth/OscilGen.cpp, src/Synth/OscilGen.h
Minimal PR, should not cause any problems. Will merge in a few days if no complaints.
=> OscilGen's Resonance can be const

src/Synth/LFO.cpp
make freq randomization reatlime
=> fix lfo parameter limit

src/Misc/Master.cpp, src/Misc/Part.cpp, src/UI/MasterUI.fl, src/UI/PartUI.fl
implementation for issue
https://github.com/zynaddsubfx/zyn-fusion-issues/issues/402
GUI Part at:
https://github.com/mruby-zest/mruby-zest-build/pull/116
=> change pkeyshift ports to have middle at 0

src/Plugin/ZynAddSubFX/ZynAddSubFX-UI-Zest.cpp
fix the loading of the zest gui as Plugin under linux
=> fix initialization of handle

src/Effects/EffectMgr.cpp, src/Effects/Reverse.cpp, src/Effects/Sympathetic.cpp
JSON with this PR
https://github.com/mruby-zest/mruby-zest-build/pull/122
=> fix defaults

doc/adsynth.txt, src/Params/ADnoteParameters.cpp, src/Params/ADnoteParameters.h, src/Synth/ADnote.cpp, src/Synth/ADnote.h, src/Tests/PortChecker.cpp, src/Tests/guitar-adnote.xmz, src/UI/ADnoteUI.fl
part from FMAA_SYNC branch
GUI: https://github.com/mruby-zest/mruby-zest-build/pull/120
=> add Oscillator Hard Sync

src/Effects/EffectMgr.cpp, src/Effects/Reverse.h, src/Misc/Time.h, src/Plugin/AbstractFX.hpp, src/Plugin/AlienWah/AlienWah.cpp, src/Plugin/AlienWah/DistrhoPluginInfo.h, src/Plugin/CMakeLists.txt, src/Plugin/Chorus/Chorus.cpp, src/Plugin/Chorus/DistrhoPluginInfo.h, src/Plugin/Distortion/Distortion.cpp, src/Plugin/Distortion/DistrhoPluginInfo.h, src/Plugin/DynamicFilter/DistrhoPluginInfo.h, src/Plugin/DynamicFilter/DynamicFilter.cpp, src/Plugin/Echo/DistrhoPluginInfo.h, src/Plugin/Echo/Echo.cpp, src/Plugin/Phaser/DistrhoPluginInfo.h, src/Plugin/Phaser/Phaser.cpp, src/Plugin/Reverb/DistrhoPluginInfo.h, src/Plugin/Reverb/Reverb.cpp, src/Plugin/Reverse/CMakeLists.txt, src/Plugin/Reverse/DistrhoPluginInfo.h, src/Plugin/Reverse/Reverse.cpp
https://github.com/zynaddsubfx/zynaddsubfx/issues/309
=> add a Reverse lv2 effect
